/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.amirunninglinux;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=com.amirunninglinux.gnu.R.drawable.ic_launcher;
    }
    public static final class id {
        public static final int webview=com.amirunninglinux.gnu.R.id.webview;
    }
    public static final class layout {
        public static final int main=com.amirunninglinux.gnu.R.layout.main;
    }
    public static final class string {
        public static final int app_name=com.amirunninglinux.gnu.R.string.app_name;
        public static final int webview_ua_base=com.amirunninglinux.gnu.R.string.webview_ua_base;
        public static final int webview_url=com.amirunninglinux.gnu.R.string.webview_url;
    }
}
